### ISSUE TITLE
Adding error handling on 'Disambiguation Error'

### ISSUE THREAD

**Issue by avinashbhat** [avinashbhat/wikicontext-v2#2]
Wikipedia API throws a Disambiguation Error if it does not understand the input given to it. One of the good fixes would be to catch the error and use the search API to display the search terms, enabling the query to be submitted again.

**Comment by avinashbhat** [comment]
Wikipedia API throws a Disambiguation Error if it does not understand the input given to it. One of the good fixes would be to catch the error and use the search API to display the search terms, enabling the query to be submitted again.

**Comment by nihaldsouza** [comment]
Fixed this for main topic since we have the select bar. But still an issue for topics in prerequisites.

**Comment by nihaldsouza** [comment]
Need to fix this for the topics in prerequisites too.

**Comment by avinashbhat** [comment]
Fixed in #10 @nihaldsouza
