### ISSUE TITLE
Certain prerequisites have no content

### ISSUE THREAD

**Issue by nihaldsouza** [avinashbhat/wikicontext-v2#6]
When generating prerequisites, sometimes the title loads but with no content. Need to eliminate these sub-topics.

Screenshot: Check prerequisite "Molecular Geometry"

<img width="800" alt="Screenshot 2020-12-05 at 10 36 24 PM" src="https://user-images.githubusercontent.com/13492776/101258694-4fbfa780-374a-11eb-9813-76b8824dc43e.png">

**Comment by avinashbhat** [comment]
Fixed in #10 @nihaldsouza
