### ISSUE TITLE
Error Handling for 'Value Error'

### ISSUE THREAD

**Issue by nihaldsouza** [avinashbhat/wikicontext-v2#7]
Search for "Polymer" using TextRank to reproduce this error.

<img width="704" alt="Screenshot 2020-12-05 at 10 43 39 PM" src="https://user-images.githubusercontent.com/13492776/101258860-53076300-374b-11eb-9e4e-c4795ecec83a.png">

**Comment by avinashbhat** [comment]
Fixed in #10 @nihaldsouza
